[package]
name = "todo_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "todo_rs"

[dependencies]

[dependencies.uuid]
version = "1.13.1"
features = [
    "v4",                # Lets you generate random UUIDs
]